### ISSUE TITLE
Switching organization accounts

### ISSUE THREAD

**Issue by ReDev1L** [moofoo/nestjs-prisma-postgres-tenancy#1]
Do you have thoughts how to implement switching tenancy by organization accounts?
User has multiple organization accounts, and the problem is switching between them, we will need many to many relation between user and tenants. And this leads to RLS problem on reading tenants, the user is assigned to.

**Comment by moofoo** [comment]
What I would do is create a bridge table connecting users to organizations to do the many-to-many relationship. Assuming you have 'users' and 'organizations'  tables, this bridge table  would look something like,

```sql
create table if not exists public.user_organizations
(
    id bigserial primary key,
    user_id bigint
        constraint user_organizations_user_id_fk
            references public.users
            on delete cascade,    
    organization_id bigint
        constraint user_organizations_organization_id_fk
            references public.organizations
            on delete cascade
);
```

It sounds like what you want  is to allow users to belong to multiple organizations, but they can only be authenticated for one at a time. So, you would presumably need to have a way for the user to pick an organization (or have it picked for them) as part of the login flow, and if the chosen org is valid per the user logging in, you would set that id in the session cookie data for the authenticated user and use it to determine tenancy for subsequent requests.

I've created a branch (based off 'main') demonstrating a possible implementation: [https://github.com/moofoo/nestjs-prisma-postgres-tenancy/tree/multi](https://github.com/moofoo/nestjs-prisma-postgres-tenancy/tree/multi)

I updated the POSTGRES.md file to match the schema changes: [https://github.com/moofoo/nestjs-prisma-postgres-tenancy/blob/multi/POSTGRES.md](https://github.com/moofoo/nestjs-prisma-postgres-tenancy/blob/multi/POSTGRES.md)

Note that you will probably need to clear your browser cache since the session data has changed

**Comment by moofoo** [comment]
didn't mean to close

**Comment by ReDev1L** [comment]
https://github.com/moofoo/nestjs-prisma-postgres-tenancy/blob/c57f5c6cdf2e28b1125305d1dde1387bd6d7ddef/db/1_schema.sql#L100

That's what I was thinking about.
Thank you for help and all this RLS implementation.

Tag / write me if you will need any help.

**Comment by moofoo** [comment]
No problem, glad I could help
